apiVersion: v1
kind: Service
metadata:
  name: okmi2t
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okmi2t"
    port: 8080
  selector:
    app: okmi2t
